// lib/documentsData.js
export const F1_DOCUMENTS = [
    {
        id: 'passport',
        title: 'Valid Passport',
        category: 'Required',
        description: 'Must be valid for at least six months beyond your period of stay in the US.',
        checked: false,
    },
    {
        id: 'i20',
        title: 'Form I-20',
        category: 'Required',
        description: 'Certificate of Eligibility for Nonimmigrant Student Status, issued by your school.',
        checked: false,
    },
    {
        id: 'ds160',
        title: 'DS-160 Confirmation Page',
        category: 'Required',
        description: 'The confirmation page with the barcode after submitting your online application.',
        checked: false,
    },
    {
        id: 'visa_fee_receipt',
        title: 'Visa Application Fee Receipt',
        category: 'Required',
        description: 'Proof that you have paid the non-refundable visa application fee.',
        checked: false,
    },
    {
        id: 'sevis_fee_receipt',
        title: 'SEVIS I-901 Fee Receipt',
        category: 'Required',
        description: 'Proof of payment for the Student and Exchange Visitor Information System fee.',
        checked: false,
    },
    {
        id: 'photo',
        title: 'Visa Photograph',
        category: 'Required',
        description: 'One 2x2 photograph meeting the specific requirements.',
        checked: false,
    },
    {
        id: 'financial_proof',
        title: 'Proof of Financial Support',
        category: 'Recommended',
        description: 'Bank statements, scholarship letters, or sponsorship affidavits showing you can cover your expenses.',
        checked: false,
    },
    {
        id: 'transcripts',
        title: 'Academic Transcripts',
        category: 'Recommended',
        description: 'Transcripts, diplomas, degrees, or certificates from schools you attended.',
        checked: false,
    },
    {
        id: 'test_scores',
        title: 'Standardized Test Scores',
        category: 'Recommended',
        description: 'TOEFL, IELTS, GRE, GMAT, etc., as required by your US school.',
        checked: false,
    },
    {
        id: 'ties_to_home',
        title: 'Proof of Ties to Home Country',
        category: 'Recommended',
        description: 'Documents showing you have strong reasons to return home after your studies (e.g., job offer, property ownership, family).',
        checked: false,
    },
]